version: '3.3'
services:
  server:
    container_name: exam_server
    build: ./server
    ports: 
      - 5001:5001
    environment:
      - PORT=5001
      - PREFIX=/api
      - NODE_ENV=production
  ui:
    container_name: exam_ui
    build: ./ui
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - API_HOST=server
      - API_PORT=5001
      - NODE_ENV=production